[project]
name = "m1n1-proxyclient"
dynamic = ["version"]
description = "M1N1 proxy client for interacting with Apple Silicon devices"
authors = [
    {name = "The Asahi Linux Contributors"}
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "construct>=2.10.70,<3.0.0",
    "pyserial>=3.5,<4.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]

[project.urls]
Homepage = "https://github.com/AsahiLinux/m1n1"
Issues = "https://github.com/AsahiLinux/m1n1/issues"

[build-system]
requires = ["setuptools>=80", "setuptools-scm==8.3.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["m1n1*", "tools*"]

#[tool.setuptools_scm]
#write_to = "m1n1/_version.py"
#search_parent_directories = true
#version_scheme = "m1n1._version_scheme:fork_post_dev_scheme"
#local_scheme = "no-local-version"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
